// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFC61lGIVxO02gcDmwS_6myTJaKxoSQ-s',
    appId: '1:1053431953264:web:f80fa56ac057a2e91c81b5',
    messagingSenderId: '1053431953264',
    projectId: 'prjpab2-si61-0015',
    authDomain: 'prjpab2-si61-0015.firebaseapp.com',
    storageBucket: 'prjpab2-si61-0015.firebasestorage.app',
    measurementId: 'G-EV01SZ27D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCpKXYBlQsK2guxujIhGD2wmvlKiBAXs',
    appId: '1:1053431953264:android:3c65aa28ba1bae5b1c81b5',
    messagingSenderId: '1053431953264',
    projectId: 'prjpab2-si61-0015',
    storageBucket: 'prjpab2-si61-0015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLf7_tL-rp-liOxS43FufxRTnnE39gB0',
    appId: '1:1053431953264:ios:edec1933b81346661c81b5',
    messagingSenderId: '1053431953264',
    projectId: 'prjpab2-si61-0015',
    storageBucket: 'prjpab2-si61-0015.firebasestorage.app',
    iosClientId: '1053431953264-5g7mvicpp0ndl8bpnh78cd8o3g5ig09s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxLf7_tL-rp-liOxS43FufxRTnnE39gB0',
    appId: '1:1053431953264:ios:edec1933b81346661c81b5',
    messagingSenderId: '1053431953264',
    projectId: 'prjpab2-si61-0015',
    storageBucket: 'prjpab2-si61-0015.firebasestorage.app',
    iosClientId: '1053431953264-5g7mvicpp0ndl8bpnh78cd8o3g5ig09s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFC61lGIVxO02gcDmwS_6myTJaKxoSQ-s',
    appId: '1:1053431953264:web:dbfde548e4a1ec631c81b5',
    messagingSenderId: '1053431953264',
    projectId: 'prjpab2-si61-0015',
    authDomain: 'prjpab2-si61-0015.firebaseapp.com',
    storageBucket: 'prjpab2-si61-0015.firebasestorage.app',
    measurementId: 'G-MKWFG0THMV',
  );
}
